# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-22 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='adventures',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='trip_planned',
        ),
    ]
