# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-22 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_auto_20180422_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='updated_at',
        ),
    ]
