# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-22 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_auto_20180422_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='end_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
